# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

[page]
# posts = "/p/:slug or content basename"

[section]
# posts = "/posts/:slug or content basename"

[taxonomy]

[term]
