description = "测试一下hugo"
keywords = ["Hugo", "FixIt"]

[author]
name = "马不前"
email = ""
link = ""
avatar = "https://api.iconify.design/game-icons:dead-eye.svg"

[app]
title = "Bones"

[header]

[header.title]
logo = "https://api.iconify.design/game-icons:dead-eye.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = ["inject/fixit-docs-bookmark.html"]
