description = "一世风尘，也只如雪泥打他人脚底经过"
keywords = ["Hugo", "FixIt"]
avatar = "https://api.iconify.design/game-icons:dead-eye.svg"

[author]
name = "马不前"
email = ""
link = ""
avatar = "https://api.iconify.design/game-icons:dead-eye.svg"

[app]
title = "Unfinished"
avatar = "https://api.iconify.design/game-icons:dead-eye.svg"

[header]

[header.title]
logo = "https://api.iconify.design/game-icons:dead-eye.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = ["inject/fixit-docs-bookmark.html"]
